### ISSUE TITLE
Missing project option in pyscripter/SpTBXLib

### ISSUE THREAD

**Issue by groehner** [pyscripter/MultiInstaller#2]
Sorry for placing this issue here, but issues aren't allowed at pyscripter/SpTBXLib

During installation of RAD Studio 11.3 Community Edition i got an error when installing the SpTBXLib packages.
Compiling SpTBXLib.bpl gives: Can't load package SpTBXLib.bpl. The system can not find the stated file.

After adding .\$(Platform)\$(Config) in "Project options\Buildung\Delpi Compiler\Unit output directory" this error is fixed.
Same for SpTBXLibDsgn.bpl

**Comment by pyscripter** [comment]
Could you please submit a PR at pyscripter/SpTBXLib for this?

Aren't you using the MultiInstaller for installing PyScripter dependencies. 

In a new installation it clones the relevant repositories and installs the dependencies. It automatically sets the search path as well.

When I want to update the dependencies:
-  I manually sync the repositories (you can do that with a script as well)
- I modify the Setup.ini by commenting out the Zip and Git lines
- Run the MultiInstaller selecting the updated components.

**Comment by pyscripter** [comment]
@groehner 
Off topic:

Your work on GuiPy is just amazing.   I will be looking into integrating some of the added stuff into PyScripter, if this is OK with you.

I see that you have added Qt support for GUI developement.  Nice!  By the way, have you looked into [delphivcl](https://github.com/Embarcadero/DelphiVCL4Python) and [delphifmx](https://github.com/Embarcadero/DelphiFMX4Python)?  Would it be difficult to provide similar support to the Qt stuff?

**Comment by groehner** [comment]
> Your work on GuiPy is just amazing. I will be looking into integrating some of the added stuff into PyScripter, if this is OK with you.
That's ok for me, because guipy is based on pyscripter.

> I see that you have added Qt support for GUI developement. Nice! 
Qt is a more modern graphics library and easier to use than Tk/TTk

> By the way, have you looked into [delphivcl](https://github.com/Embarcadero/DelphiVCL4Python) and [delphifmx](https://github.com/Embarcadero/DelphiFMX4Python)? Would it be difficult to provide similar support to the Qt stuff?

I think you need delphivcl to build a gui form with the help of delphi in python.
But in python you have direct access to Qt.  So i haven't got your point.

I also have a question:
Teachers ask me if there is a Mac version of GuiPy because they have students with Macs at home.
Do you think it would be possible to create a Mac version of GuiPy, or are there insurmountable obstacles?

**Comment by pyscripter** [comment]
> I think you need delphivcl to build a gui form with the help of delphi in python.
> But in python you have direct access to Qt. So i haven't got your point.

You can install delphivcl/delphifmx with pip, just like you do with Qt.

> Teachers ask me if there is a Mac version of GuiPy because they have students with Macs at home.
> Do you think it would be possible to create a Mac version of GuiPy, or are there insurmountable obstacles?

I would very much like that, but it wouldn't be easy.   It will have to be FMX and many of the components used including SynEdit are not available in FMX.   It may be easier to convert the project to fpc+Lazarus instead.
